### ISSUE TITLE
Error pty.Start

### ISSUE THREAD

**Issue by xperiafan13-rom** [integrii/headlessChrome#1]
..\github.com\integrii\interactive\session.go:86:15: undefined: pty.Start

**Comment by integrii** [comment]
I can't seem to reproduce this.  This seems to point to `github.com/kr/pty` not having a `Start()` function, but it does: https://github.com/kr/pty/blob/ce7fa45920dc37a92de8377972e52bc55ffa8d57/run.go#L14

Do you have a _very_ old version of this package already?  Can you do a `go get -u` on your project?
